name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt update && sudo apt install libmariadb-dev libmariadbclient-dev
    - name: make
      run: make
