name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt update && sudo apt install libmariadb-dev libmariadbclient-dev
    - name: make
      run: make
    - name: archive production artifact
      uses: actions/upload-artifact@v1
      with:
        name: SHT20toDB_x86
        path: SHT20toDB
